site_name: R-AID Documentation
repo_url: https://github.com/shibaji7/R-AID
theme: 
  name: "material"
  logo: assets/RAID-2.png
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

plugins:
    - search
    - glightbox
    - mkdocstrings:
        enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
        custom_templates: templates
        default_handler: python
        handlers:
          python:
            options:
              show_source: true
     
markdown_extensions:
    - extra
    - admonition
    - toc
    - attr_list
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
        
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Installation: user/install.md  
    - Riometer Data Access: user/riometers.md
    - HamSCI PSWS Data Access: user/hamsci.md
